### ISSUE TITLE
Setup Room-DB with the project.

### ISSUE THREAD

**Issue by rasheedsulayman** [CottaCush/AndroidBaseProjectKotlin#2]
Requirement: Provide a base/generic setup for Room-DB and add it to the DI setup/graph.
 
Optional requirement: Use the Room-DB setup in the sample project. Making the cats data available offline would provide a good sample usage.

**Comment by falayy** [comment]
I've set this up, you might want to close the issue when you're satisfied.

**Comment by rasheedsulayman** [comment]
Fixed in #5
