### ISSUE TITLE
Add unit tests for the sample project.

### ISSUE THREAD

**Issue by rasheedsulayman** [CottaCush/AndroidBaseProjectKotlin#3]
- Add the necessary dependencies for unit tests. check out [androidxTest](https://developer.android.com/training/testing/set-up-project#add-android-test-libraries), [truth](https://github.com/google/truth), [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) etc. 

- Write unit tests for the sample project.

**Comment by JohnItoo** [comment]
@r4sh33d is anyone working on this ?

**Comment by JohnItoo** [comment]
I have some capacity

**Comment by rasheedsulayman** [comment]
@corneliuze started working on testing the room DB.  You can work on testing the repositories/ViewModels for the sample app.

**Comment by JohnItoo** [comment]
Great.

**Comment by JohnItoo** [comment]
First iteration of this has been merged. As the sample projects gets bigger. we can write more unit  tests.
